apiVersion: apps/v1
kind: Deployment
metadata:
  name: vendra-queue
  namespace: vendra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vendra-queue
  template:
    metadata:
      labels:
        app: vendra-queue
    spec:
      containers:
      - name: queue
        image: registry.digitalocean.com/vendra-registry/vendra-queue:latest
        envFrom:
        - configMapRef:
            name: vendra-config
        env:
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: vendra-secret
              key: APP_KEY
        - name: APP_URL
          valueFrom:
            secretKeyRef:
              name: vendra-secret
              key: APP_URL
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: vendra-secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vendra-secret
              key: DB_PASSWORD
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "150m"
