apiVersion: v1
kind: Secret
metadata:
  name: vendra-secret
  namespace: vendra
type: Opaque
stringData:
  APP_KEY: "base64:D5YV+aERCYjZYKrXUK5NIHZH75Der2yokFvHpnLx61Q="
  APP_URL: "https://einv.palbillr.com"
  DB_USERNAME: "vendra"
  DB_PASSWORD: "nB/LoMJCH0Gx46Bse8WOFrgZl34U7VIC"
  MYSQL_ROOT_PASSWORD: "SdQOnmuEHyVID+tVzyGGqAVnugAvCsuj"
  APP_NAME: "Palbillr"
  APP_ENV: local
  APP_KEY: base64:J1VFAHD946ny8xO6IR9AI/GB5qYBRU4l1zTlXW5oGq0=
  APP_DEBUG: "true"
  APP_URL: https://einv.palbillr.com

  APP_LOCALE: "en"
  APP_FALLBACK_LOCALE: "en"
  APP_FAKER_LOCALE: "en_US"

  APP_MAINTENANCE_DRIVER: "file"
  # APP_MAINTENANCE_STORE=database

  PHP_CLI_SERVER_WORKERS: "4"

  BCRYPT_ROUNDS: "12"

  LOG_CHANNEL: "stack"
  LOG_STACK: "single"
  LOG_DEPRECATIONS_CHANNEL: "stack"
  LOG_DEPRECATIONS_STACK: "single"
  LOG_LEVEL: "debug"

  SESSION_DRIVER: "database"
  SESSION_LIFETIME: "120"
  SESSION_ENCRYPT: "false"
  SESSION_PATH: "/"
  SESSION_DOMAIN: ""

  BROADCAST_CONNECTION: "log"
  FILESYSTEM_DISK: "local"
  QUEUE_CONNECTION: "database"

  CACHE_STORE: "database"
  # CACHE_PREFIX=

  MEMCACHED_HOST: "127.0.0.1"
  MEMCACHED_PORT: "11211"

  REDIS_CLIENT: "phpredis"
  REDIS_HOST: "127.0.0.1"
  REDIS_PASSWORD: ""
  REDIS_PORT: "6379"

  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_DEFAULT_REGION: "us-east-1"
  AWS_BUCKET: ""
  AWS_USE_PATH_STYLE_ENDPOINT: "false"

  VITE_APP_NAME: "${APP_NAME}"

  TAXLY_API_KEY: "43dbf9debb5bf81c2e952dc00d047b796de9f4dcf67decd19397f14af9f6d901"
  TAXLY_BASE_URL: "https://taxly.ng/api/v1"
  TAXLY_INTEGRATOR_SERVICE_ID: "109029"

  FIRS_PUBLIC_KEY: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFyU0xpdDRtb1RMbFdjd1A4eEp6RQp3ZTdkRHExdC9kMi9zcXdQTlNVandablFPbklabVh4TXY4QUQxemMxdUErZ3VCc2tpUGdoSXd6ekxWYXJoNk1KCndEdVUxSC95V2FPZE1PTnZOQy9OWERybXB5cE5WUDZyQnV3LzVjSERMdEtoZlJ0YkdFa1JSVVF4MVAxUUJ6REsKVVRpaTRJOXJld29zcVQ4V1dBOE8zRVd5ZHJ5TEg1K3JpVmRUNVBPeU1jcU95YUR2bGRqWG9ZdnBSTHlkcmtDQQpkUWpMdkw0bG00TVNxS05WdGVJR0Y4ZWk4M3Juck5wR3hKTVVGYVMwekt5TzBJZlY0alBCK3ZXN3I1TXdzTjRvCkRnWVR2ME85Q050N3JoNlEvYi9XR3Ewakl3WHJ3c3JIQXE4TXNyUVlGV0JIOHpmejMwOHRWMTlRM1hPTnEyWEMKMHdJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg=="
  FIRS_CERTIFICATE: "NklBL25zYU9QOGc3TXpRWStobE9WdlBQZlovbFIwM1hkdjlkNGI4UkNzQT0="
